- name: Create project
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_name: "ansible_testing_project"
  
  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: "Include role openshift_namespace"
      include_role:
        name: openshift_namespace
      vars:
        openshift_namespace_name: "{{ project_name }}"

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
