- name: Create project
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_name: foo

  tasks:
    - name: "Block to to do whatevs"
      block:
        - name: "Include role openshift_username_password_auth"
          ansible.builtin.include_role:
            name: openshift_username_password_auth
          vars:
            auth_action: login

        - name: "Include role openshift_namespace"
          ansible.builtin.include_role:
            name: openshift_namespace
          vars:
            openshift_namespace_name: "{{ project_name }}"

      always:
        - name: "Include role openshift_username_password_auth"
          ansible.builtin.include_role:
            name: openshift_username_password_auth
          vars:
            auth_action: logout
