- name: Create project
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_name: "ansible_testing_project"
    bridge_name: "br1"

  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: "Include role openshift-namespace"
      include_role:
        name: openshift-namespace
      vars:
        openshift_namespace_name: "{{ project_name }}"

    - name: "Include role openshift_networkbridge"
      include_role:
        name: openshift_networkbridge
      vars:
        openshift_networkbridge_namespace: "{{ project_name }}"
        openshift_networkbridge_bridge_interface: "{{ bridge_name }}"

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
