- name: List Pods
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        api_key: "{{ api_key }}"
        kind: Pod
      register: pod_list

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
