- name: List Pods
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name:
    vm_namespace:

  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: " get information about virtual machine {{ vm_name }}"
      kubernetes.core.k8s_info:
        api_key: "{{ api_key }}"
        kind: Pod
        label_selectors:
          - "vm.kubevirt.io/name = {{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info

    - name: Print vm_info
      ansible.builtin.debug:
        var: vm_info.resources[0].status

    - name: Set variable storing bridge IP address
      set_fact:
        vm_bridge_ip_address: "{{ vm_info | json_query(query) }}"
      vars:
        query: "resources[].status.hostIP"
  
    - name: Display bridge IP address
      debug:
        msg: "{{ vm_bridge_ip_address }}"

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
