- name: Create virtual machine
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    vm_name:
    template_name:
    project_name:
    size:
    bridge:
    bridge_name:

  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: "Include role openshift_namespace"
      include_role:
        name: openshift_namespace
      vars:
        openshift_namespace_name: "{{ project_name }}"

    - name: "Include role openshift_networkbridge"
      include_role:
        name: openshift_networkbridge
      vars:
        openshift_networkbridge_namespace: "{{ project_name }}"
        openshift_networkbridge_bridge_interface: "{{ bridge_name }}"

    - name: "Include role openshift_vm"
      include_role:
        name: openshift_vm
      vars:
        openshift_vm_action: create
        openshift_vm_name: "{{ vm_name }}"
        openshift_vm_namespace: "{{ project_name }}"
        openshift_vm_size: "{{ size }}"
        openshift_vm_source_pvc_name:

    - name: Print vm bridge ipv4 address
      ansible.builtin.debug:
        var: bridge_ipv4_address

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
