- name: Stop all virtual machines in a namespace
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_name:

  tasks:
  - block:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: login

    - name: "Include role openshift_vm"
      include_role:
        name: openshift_vm
      vars:
        openshift_vm_action: stop_all
        openshift_vm_namespace: "{{ project_name }}"

    always:
    - name: "Include role openshift_username_password_auth"
      include_role:
        name: openshift_username_password_auth
      vars:
        auth_action: logout
